use std::process::Command;

const DESTINATION_TS_BINDINGS: &str = "../src/ts/bindings.ts";
const HEADER_NOTE : &str = "This is has been generated by typeshare and edited with search and replace to insert the equivalent of some unknown types.\n You can see how it works in desktop/src-tauri/build.rs where the typeshare CLI is being run.";
const TS_BINDINGS_REPLACEMENTS: &[(&str, &str)] = &[("DateTime<Utc>", "number")];

fn main() {
    // Existing tauri build
    tauri_build::build();

    // Generate TypeScript types from Rust structs annotated with #[typeshare]
    // Note: this command is ran in this folder src-tauri, even though we run "pnpm run dev" under desktop/
    let res = Command::new("typeshare")
        .args(vec![
            "../..",
            "--lang=typescript",
            format!("--output-file={DESTINATION_TS_BINDINGS}").as_str(), // this is desktop/src/bindings.ts
        ])
        .output()
        .expect("\nMAKE SURE YOU HAVE THE TYPESHARE CLI installed !\nYou can install it with:\ncargo install typeshare-cli\n\n\n");
    assert!(
        res.status.success(),
        "\nTYPESHARE TYPES GENERATION FAILURE:\n\n{}",
        String::from_utf8(res.stderr).unwrap()
    );

    let mut content = std::fs::read_to_string(DESTINATION_TS_BINDINGS).unwrap();
    // Manage TS_BINDINGS_REPLACEMENTS
    let mut replacement_resume = String::new();
    for (from, to) in TS_BINDINGS_REPLACEMENTS {
        content = content.replace(from, to);
        replacement_resume.push_str(format!(" {from} -> {to}\n").as_ref());
    }
    // Insert the HEADER_NOTE in the existing comment
    content = content.replace(
        "Generated by typeshare",
        format!("{HEADER_NOTE}\n List of replacements:\n{replacement_resume}\n After generation by typeshare").as_str(),
    );
    std::fs::write(DESTINATION_TS_BINDINGS, content)
        .expect("Couldn't save modified file {DESTINATION_TS_BINDINGS}");

    // Tell Cargo to rerun this script if these files/folders change
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=../..");
}
