
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getLocalCourses() : Promise<CourseInfo[]> {
    return await TAURI_INVOKE("get_local_courses");
},
async cloneCourse(repos: string) : Promise<boolean> {
    return await TAURI_INVOKE("clone_course", { repos });
},
async highlightCodeWithTreeSitter(file: string, code: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("highlight_code_with_tree_sitter", { file, code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadDefaultThemeCss() : Promise<string> {
    return await TAURI_INVOKE("load_default_theme_css");
},
async loadFullCourseDetails(coursePath: string, exoStatusUiChannel: TAURI_CHANNEL<ExoStatusReport>) : Promise<Result<Project, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_full_course_details", { coursePath, exoStatusUiChannel }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderMarkdownWithHighlighting(content: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("render_markdown_with_highlighting", { content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sendUiActionToApp(action: UiAction) : Promise<void> {
    await TAURI_INVOKE("send_ui_action_to_app", { action });
}
}

/** user-defined events **/



/** user-defined constants **/

export const PROTOCOL_VERSION = "0.1.0" as const;
export const QUERYSTRING_LIVE_CLIENT_ID_FIELD = "live_client_id" as const;
export const DEFAULT_LIVE_PORT = 9120 as const;
export const QUERYSTRING_LIVE_PROTOCOL_VERSION_FIELD = "live_protocol_version" as const;

/** user-defined types **/

/**
 * Represents a Exo Check
 */
export type Check = { name: string; args?: string[]; test: CheckTest }
/**
 * Handles the check and it's current status
 */
export type CheckState = { check: Check; status: CheckStatus }
/**
 * Represents the status of a check
 */
export type CheckStatus = { type: "Passed" } | { type: "Failed"; content: { expected: string; given: string; diff: string } } | { type: "Checking" } | { type: "Running" } | { type: "RunFail"; content: string } | { type: "Pending" }
/**
 * Represents the actual check type
 */
export type CheckTest = { type: "Output"; expected: string }
export type CourseInfo = { name: string; folder: string; config: LiveConfig | null }
/**
 * Represents a Plx Exo
 */
export type Exo = { name: string; instruction: string | null; state: ExoState; files: string[]; solutions: string[]; checks: Check[]; favorite: boolean; folder: string }
/**
 * ExoCheckResult
 * 
 * This struct is used to store the result of a run + check
 * Each exo run will have as many ExoCheckResults as the number of checks the exo has
 * This helps us keep the output of the run and the check state together
 */
export type ExoCheckResult = { state: CheckState; output: string[] }
export type ExoState = "Todo" | "InProgress" | "Done"
/**
 * ExoStatusReport
 * 
 * This struct is used to store the result of a run + check
 * It keeps the information of an exo run, including the check results,
 * the compilation output and the path to the elf file
 * See `ExoCheckResult` for more information about the check results
 */
export type ExoStatusReport = { check_results: ExoCheckResult[]; compilation_output: string[]; compilation_success: boolean; compilation_running: boolean }
export type LiveConfig = { domain: string; port: number; group_id: string }
export type Project = { name: string; skills: Skill[]; folder: string }
export type Skill = { name: string; path: string; exos: Exo[] }
export type TAURI_CHANNEL<TSend> = null
/**
 * An action requested by the UI
 */
export type UiAction = { type: "StartExo"; content: { exo_folder: string } } | { type: "StopExo" } | 
/**
 * Stop the App instance and all the workers
 */
{ type: "StopApp" }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
