
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getLocalCourses() : Promise<CourseInfo[]> {
    return await TAURI_INVOKE("get_local_courses");
},
async cloneCourse(repos: string) : Promise<boolean> {
    return await TAURI_INVOKE("clone_course", { repos });
},
async openCourse(path: string) : Promise<Result<CourseInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_course", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSessions() : Promise<Result<Session[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startSession(name: string) : Promise<Result<Session, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_session", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async joinSession(session: Session) : Promise<Result<Session, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("join_session", { session }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/

export const QUERYSTRING_LIVE_CLIENT_ID_FIELD = "live_client_id" as const;
export const PROTOCOL_VERSION = "0.1.0" as const;
export const DEFAULT_LIVE_PORT = 9120 as const;
export const QUERYSTRING_LIVE_PROTOCOL_VERSION_FIELD = "live_protocol_version" as const;

/** user-defined types **/

export type CourseInfo = { name: string; folder: string }
/**
 * A live session, this is the representation sent to clients
 * when listing all sessions or after session creation
 */
export type Session = { 
/**
 * An arbitrary name defined by the leader to help followers choose the correct sessions
 * among the multiple live sessions at the same time on the same group_id
 * We imagine it could be named like "Course name - Teacher fullname"
 */
name: string; 
/**
 * The group id is a way to group related sessions together.
 * This can be an arbitrary string chosen by leader clients when creating a session.
 * Listing available sessions can only be done via this group_id to filter the list
 * By default, PLX clients will send the Git HTTPS link
 */
group_id: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
