/*
 This is has been generated by typeshare and edited with search and replace to insert the equivalent of some unknown types.
 You can see how it works in desktop/src-tauri/build.rs where the typeshare CLI is being run.
 List of replacements:
 DateTime<Utc> -> number
 PathBuf -> string
 ParseError -> string

 After generation by typeshare 1.13.3
*/

/**
 * A incremental number attributed by the server to each client after session join, to let clients identify other clients.
 * This MUST NOT be derived from the secret client_id, this ClientNum is not secret but should be different at each session.
 */
export type ClientNum = number;

/** Represents the status of a check */
export type DetailledCheckStatus = 
	| { type: "Passed", content?: undefined }
	| { type: "Failed", content: {
	expected: string;
	given: string;
	diff: Diff;
}}
	| { type: "Checking", content?: undefined }
	| { type: "Running", content?: undefined }
	| { type: "RunFail", content: string }
	| { type: "Pending", content?: undefined };

/** Handles the check and it's current status */
export interface CheckWithStatus {
	check: Check;
	status: DetailledCheckStatus;
}

export interface Course {
	name: string;
	code: string;
	goal: string;
	skills: Skill[];
	folder: string;
}

export interface CourseWithErrors {
	course: Course;
	errors: string[];
}

export type CheckStatus = 
	| { type: "Passed", content?: undefined }
	| { type: "CheckFailed", content: string }
	| { type: "BuildFailed", content: string }
	| { type: "RunFailed", content: string };

export interface ExoCheckResult {
	index: number;
	state: CheckStatus;
}

/**
 * ExoCheckResult
 * 
 * This struct is used to store the result of a run + check
 * Each exo run will have as many ExoCheckResults as the number of checks the exo has
 * This helps us keep the output of the run and the check state together
 */
export interface ExoCheckResultWithOutput {
	state: CheckWithStatus;
	output: string[];
}

/**
 * ExoStatusReport
 * 
 * This struct is used to store the result of a run + check
 * It keeps the information of an exo run, including the check results,
 * the compilation output and the path to the elf file
 * See `ExoCheckResult` for more information about the check results
 */
export interface ExoStatusReport {
	check_results: ExoCheckResultWithOutput[];
	compilation_output: string;
	compilation_success: boolean;
	compilation_running: boolean;
	elf_path: string;
	exo: Exo;
}

export interface ForwardedFile {
	/** The relative path inside the exo folder, like "main.cpp", "src/main.rs", "lib/image.h" */
	path: string;
	content: string;
	/** The time where this code was received on the server */
	time: number;
}

export interface ForwardedResult {
	/** The relative path inside the exo folder, like "main.cpp", "src/main.rs", "lib/image.h" */
	check_result: ExoCheckResult;
	/** The time where this result was received on the server */
	time: number;
}

export interface LiveConfig {
	domain: string;
	port: number;
	group_id: string;
}

/**
 * A live session, this is the representation sent to clients
 * when listing all sessions or after session creation
 */
export interface Session {
	/**
	 * An arbitrary name defined by the leader to help followers choose the correct sessions
	 * among the multiple live sessions at the same time on the same group_id
	 * We imagine it could be named like "Course name - Teacher fullname"
	 */
	name: string;
	/**
	 * The group id is a way to group related sessions together.
	 * This can be an arbitrary string chosen by leader clients when creating a session.
	 * Listing available sessions can only be done via this group_id to filter the list
	 * By default, PLX clients will send the Git HTTPS link
	 */
	group_id: string;
}

export interface SessionStats {
	followers_count: number;
	leaders_count: number;
}

/** The protocol defines a set of valid actions that only clients can send */
export type Action = 
	| { type: "StartSession", content: {
	name: string;
	group_id: string;
}}
	| { type: "StopSession", content?: undefined }
	| { type: "JoinSession", content: {
	name: string;
	group_id: string;
}}
	| { type: "LeaveSession", content?: undefined }
	| { type: "GetSessions", content: {
	group_id: string;
}}
	| { type: "SwitchExo", content: {
	path: string;
}}
	| { type: "SendFile", content: {
	path: string;
	content: string;
}}
	| { type: "SendResult", content: {
	check_result: ExoCheckResult;
}};

/** The role of a client attributed when has joined a session */
export enum ClientRole {
	/** Default role, for anyone following a session */
	Follower = "Follower",
	/**
	 * When the client creates a session, it becames a leader client.
	 * When the session is stopped, it become a `Follower` again.
	 */
	Leader = "Leader",
}

/**
 * The server can send some events to one, some or all clients of the session
 * These events are generated after an action, in this case they are not necessarily sent to the
 * author of the action, but could sent to other clients.
 * These events can also be generated directly by the server (after some timeout or OS signal received)
 */
export type Event = 
	| { type: "SessionStopped", content?: undefined }
	| { type: "SessionJoined", content: ClientNum }
	| { type: "SessionLeaved", content?: undefined }
	| { type: "SessionsList", content: Session[] }
	| { type: "Stats", content: SessionStats }
	| { type: "ServerStopped", content?: undefined }
	| { type: "ExoSwitched", content: {
	path: string;
}}
	| { type: "ForwardFile", content: {
	client_num: ClientNum;
	file: ForwardedFile;
}}
	| { type: "ForwardResult", content: {
	client_num: ClientNum;
	result: ForwardedResult;
}}
	| { type: "Error", content: LiveProtocolError };

/**
 * An error sent from the server to clients after any message
 * that resolved in an error that is worth sending back to the client
 */
export type LiveProtocolError = 
	| { type: "FailedToStartSession", reason: string }
	| { type: "FailedToJoinSession", reason: string }
	| { type: "FailedSendingWithoutSession", reason?: undefined }
	| { type: "FailedToLeaveSession", reason?: undefined }
	| { type: "SessionNotFound", reason?: undefined }
	| { type: "CannotJoinOtherSession", reason?: undefined }
	| { type: "ForbiddenSessionStop", reason?: undefined }
	| { type: "ActionOnlyForLeader", reason: string };

